version: "3.3"
services:
  app:
    image: employee-image
    container_name: employee-app
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=${PG_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${PG_PASSWORD}
      - ACTIVEMQ_URL=tcp://queue:61616
      - PORT=8080
    ports:
      - 80:8080
    depends_on:
      - db
      - queue
  db:
    image: postgres:9.5-alpine
    container_name: employee-postgres
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    command: -c 'max_prepared_transactions=100'
    volumes:
      - employee_db_vol:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432
  queue:
    image: webcenter/activemq
    container_name: activemq
    ports:
      - ${ACTIVEMQ_TCP_PORT}:61616
      - ${ACTIVEMQ_WEB_CONSOLE_PORT}:8161
volumes:
  employee_db_vol: